### ISSUE TITLE
quantization/ncnn2table params

### ISSUE THREAD

**Issue by txdat** [pengtougu/ncnn-yolov4-int8#1]
thanks for your project, I don't know how you generate table file. I have read your article on zhihu, but I don't know about ncnn2table's params: `mean=[104,117,123]`, `norm=[0.017,0.017,0.017]` and `pixel=BGR` (while yolov4 uses `PIXEL_BGR2RGB`). Thanks a lot!

**Comment by ppogg** [comment]
good，If you want to know how those params came about, I'll give you some information and you should get the idea

ncnn的norm和mean计算公式：https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#pre-process
coco的mean和norm：
mean=【120.105，114.24，104.04】
norm=【0.0167，0.0164，0.0174】

ncnn操作参数权重表：https://github.com/Tencent/ncnn/wiki/operation-param-weight-table

**Comment by txdat** [comment]
I have a question, in ncnn's document, `mean and norm are the values you passed to Mat::substract_mean_normalize()`, it means `mean={0, 0, 0}` and `norm={1 / 255.f, 1 / 255.f, 1 / 255.f}` with [yolov4](https://github.com/Tencent/ncnn/blob/master/examples/yolov4.cpp#L98), not above values. Thanks!

**Comment by ppogg** [comment]
这个是可以改的，不唯一，你可以多试验一下，但是你要确保做校验表的mean和norm要和你cpp代码里面的mean和norm一致

**Comment by ppogg** [comment]
> I have a question, in ncnn's document, `mean and norm are the values you passed to Mat::substract_mean_normalize()`, it means `mean={0, 0, 0}` and `norm={1 / 255.f, 1 / 255.f, 1 / 255.f}` with [yolov4](https://github.com/Tencent/ncnn/blob/master/examples/yolov4.cpp#L98), not above values. Thanks!

并且，很有趣的是，不同的mean和norm会影响模型量化后的速度，这个你可以尝试下，是个非常sexy的点
