### ISSUE TITLE
int8 fp16速度比较

### ISSUE THREAD

**Issue by zhangluustb** [pengtougu/ncnn-yolov4-int8#3]
“对比之前的fp16模型，明显在input_size相同的情况下快了40%-70%，且精度几乎没有什么损耗”

但是我看到表中int8反而更慢，是这样吗？有分析过为什么吗？

**Comment by ppogg** [comment]
你需要在arm上进行测试，ncnn主要还是为芯片而设计，正常情况下，在arm架构的芯片上，int8量化的模型一般会比fp16快一些：
![image](https://user-images.githubusercontent.com/82716366/130578546-32a13c36-0000-4f83-a279-f3330c10455d.png)

**Comment by ppogg** [comment]
哦，我知道了，表里面的两个数据是反的，谢谢提醒~
